### ISSUE TITLE
Add an option to choose which side the dragon swings in

### ISSUE THREAD

**Issue by elyalon** [ryguy2k4/ryguy2k4endpractice#1]
Maybe even just for diagonal perches since you need a setup for each side, it would just be so much nicer to be able to practice 1 side at a time without having the other setup block your view.
Also we recently realized that if the dragon perches faster than 47.5s-ish which is necessary for WR, it always swings to the left so it's kind of pointless to practice right side.

**Comment by ryguy2k4** [comment]
Sure thing. I'll have it done in a few days.

**Comment by ryguy2k4** [comment]
I released it, let me know if there are any problems :)
